#' @export
use_modules <- function(folder = ".") {
  addConfigure(folder)
  initModules(folder)
}

addConfigure <- function(folder = ".") {
  folder <- normalizePath(folder)
  message(sprintf("Creating %s[.win]", configureFile <- normalizePath(paste0(folder, "/configure"))))
  code <- c(
    '#!/bin/sh', '',
    '$R_HOME/bin/Rscript -e "modules::initModules()"',
    '')
  writeLines(code, configureFile)
  writeLines(code, configureFileWin <- paste0(configureFile, ".win"))
  Sys.chmod(configureFile, "0764")
  Sys.chmod(configureFileWin, "0764")
}

#' @export
initModules <- function(folder = ".", where = parent.frame()) {
  message("** modules")
  folder <- normalizePath(paste0(folder, "/R"), mustWork = FALSE)
  removeOutdatedModules(folder)
  processModules(folder)
  invisible(NULL)
}

removeOutdatedModules <- function(folder) {
  subFiles <- getSubFiles(folder)
  for (file in subFiles) {
    moduleFolder <- sub("modules-", "", sub("\\.[rR]$", "", file))
    if (!dir.exists(moduleFolder)) {
      message(sprintf("*** removing %s: no module folder found", file))
      file.remove(file)
    }
  }
}

processModules <- function(folder) {
  subFolders <- getSubFolders(folder)
  subFiles <- constSubFiles(folder)
  subNames <- getSubNames(folder)
  mapply(parseAndWrite, subFolders, subNames, subFiles)
}

parseAndWrite <- function(subFolder, subName, subFile) {
  code <- parseModule(subFolder, subName)
  if (!file.exists(subFile)) message("*** creating %s", subFile)
  writeLines(code, subFile)
}

parseModule <- function(subFolder, subName) {
  code <- lapply(list.files(subFolder, "\\.[rR]$", full.names = TRUE), readLines)
  code <- unlist(code)
  doc <- code[grepl(" *#+'", code)]
  code <- code[!grepl(" *#+'", code)]
  code <- ifelse(code == "", code, paste0("  ", code))
  assignConst <- sprintf("new%s <- function() modules::module({", subName)
  assignModule <- sprintf("%s <- new%1$s()", subName)
  closingParans <- sprintf("})")
  c(disclaimer(), assignConst, code, closingParans, "\n", doc, assignModule)
}

disclaimer <- function() "# Generated by modules: do not edit by hand\n"

getSubFolders <- function(folder) {
  dirs <- list.dirs(folder, recursive = FALSE)
  dirs[basename(dirs) != "modules"]
}

getSubNames <- function(folder) {
  basename(getSubFolders(folder))
}

getSubFiles <- function(folder) {
  list.files(folder, "modules-.*\\.[rR]$", full.names = TRUE)
}

constSubFiles <- function(folder) {
  subNames <- getSubNames(folder)
  if (length(subNames) == 0) character(0)
  else paste0(folder, "/modules-", subNames, ".R")
}
